In [2]:
import numpy as np
import pandas as pd

In [2]:
rulesDF = pd.read_csv('rules_DF.csv')

In [4]:
rulesDF

,Unnamed: 0,uuid,rules
0,0,0003caab-9ff5-5d1a-bc06-976dd0457f19,You can choose to put the basic land card into...
1,1,0003d249-25d9-5223-af1e-1130f09622a7,"The ""enters"" ability is mandatory. If you're t..."
2,2,0004a4fb-92c6-59b2-bdbe-ceb584a9e401,Rule of Law looks at the entire turn to see if...
3,3,000a83dc-9ee4-528d-866d-2ca2063e718c,If a permanent or suspended card has only one ...
4,4,000c11aa-96b1-5d10-9bd1-d037a3bba655,Some effects can prevent creatures from untapp...
...,...,...,...
14566,14566,ffe2f826-0559-576d-b0c7-065d3e2621b6,You can't activate Lochmere Serpent's last abi...
14567,14567,ffe434d9-65a5-5182-847a-caf8c4323443,"Except for the listed exceptions, the token co..."
14568,14568,ffe47585-2b2f-58ef-8662-9da55112badc,Cemetery Illuminator's ability allows you to c...
14569,14569,fff04c4b-9476-536e-871a-69c53711b8ec,You cast the card before shuffling your librar...
14570,14570,fff91eab-59ee-5d56-abde-243fcec668d5,Tendril of the Mycotyrant's ability doesn't ha...

In [3]:
processedDF = pd.read_csv('mtg_processed.csv')

In [6]:
# 2. (Optional) Clean up any unnecessary columns, like the unlabeled index column in rules_DF
if 'Unnamed: 0' in rulesDF.columns:
    rulesDF = rulesDF.drop(columns=['Unnamed: 0'])

# 3. Merge the dataframes on 'uuid'
# Using how='inner' keeps only rows where the uuid exists in BOTH datasets.
# If you want to keep all cards even if they don't have rules, use how='left'.
merged_df = pd.merge(processedDF, rulesDF, on='uuid', how='inner')

# 4. Save the result to a new CSV
merged_df.to_csv('merged_mtg_rules.csv', index=False)

In [3]:
df = pd.read_csv('merged_mtg_rules.csv')

In [4]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Read the data
df = pd.read_csv('merged_mtg_rules.csv')

# Drop NaNs for the type column
types = df['type'].dropna()

# 1. Distribution Bar Chart (Top 20 most frequent types)
plt.figure(figsize=(12, 8))
type_counts = types.value_counts().head(20)
# Updated to avoid FutureWarning: assigned 'hue' and set 'legend=False'
sns.barplot(x=type_counts.values, y=type_counts.index, hue=type_counts.index, palette='viridis', legend=False)
plt.title('Top 20 Most Frequent Card Types', fontsize=16)
plt.xlabel('Count', fontsize=12)
plt.ylabel('Card Type', fontsize=12)
plt.tight_layout()
plt.savefig('type_distribution_bar_chart.png')
plt.close()

# 2. Histogram
# Since 'type' is categorical, a strict histogram applies to numerical data.
# We will create a histogram of the *string lengths* of the types to satisfy the histogram request,
# and also extract the "Base Type" (e.g. Creature, Instant) for another perspective.

df['base_type'] = types.apply(lambda x: x.split('—')[0].strip() if isinstance(x, str) else x)
base_type_counts = df['base_type'].value_counts().head(20)

plt.figure(figsize=(12, 8))
# Updated to avoid FutureWarning: assigned 'hue' and set 'legend=False'
sns.barplot(x=base_type_counts.values, y=base_type_counts.index, hue=base_type_counts.index, palette='magma', legend=False)
plt.title('Distribution of Base Card Types', fontsize=16)
plt.xlabel('Count', fontsize=12)
plt.ylabel('Base Card Type', fontsize=12)
plt.tight_layout()
plt.savefig('base_type_distribution.png')
plt.close()

# Histogram of frequencies (how many types appear 1 time, 2 times, etc.)
plt.figure(figsize=(10, 6))
all_type_counts = types.value_counts()
plt.hist(all_type_counts, bins=50, color='skyblue', edgecolor='black', log=True)
plt.title('Histogram of Card Type Frequencies (Log Scale)', fontsize=16)
plt.xlabel('Frequency of a specific Card Type', fontsize=12)
plt.ylabel('Number of Unique Card Types (Log Scale)', fontsize=12)
plt.tight_layout()
plt.savefig('type_frequency_histogram.png')
plt.close()

print("Plots generated successfully without warnings.")

Plots generated successfully without warnings.

In [7]:
df['type'].unique().sum()

"InstantCreature — SphinxCreature — SliverCreature — Vampire WarriorEnchantment — AuraSorceryEnchantmentLegendary Creature — Human VillainLandEnchantment — SagaLegendary Creature — Bird SerpentCreature — Human WarlockArtifact Creature — Cyborg AdvisorCreature — Kor ArtificerCreature — Human WizardCreature — Elemental IncarnationSorcery — AdventureLegendary Creature — Human WizardCreature — Elf WarriorArtifactLegendary Creature — Human DruidCreature — DinosaurCreature — Jellyfish RogueCreature — Dwarf BarbarianCreature — ElementalCreature — Human SoldierLegendary Planeswalker — NarsetLegendary Planeswalker — SerraLegendary Creature — Cat WarriorCreature — Satyr RogueCreature — KavuArtifact Creature — Insect ThopterCreature — Rat NinjaLegendary Planeswalker — JaceCreature — Giant SoldierCreature — SpiritLegendary Creature — Elf ArtificerCreature — Eldrazi WerewolfCreature — Goblin WarriorLegendary Creature — Elf NobleCreature — Human ArtificerLegendary Creature — Cat ClericCreature — Vampire RogueLand — Forest PlainsCreature — Human OozeCreature — ShapeshifterArtifact — VehicleLegendary Artifact LandLegendary Creature — Cat DemonLegendary Enchantment — BackgroundCreature — Vedalken WizardCreature — SnakeCreature — Zombie HorrorArtifact Creature — BeastCreature — Ox MountCreature — Human WerewolfEnchantment Creature — Human NinjaInstant — ArcaneCreature — Elemental TurtleCreature — Giant WarriorCreature — WurmArtifact — EquipmentCreature — EldraziCreature — Vampire NobleCreature — Rhino SoldierLegendary Creature — BeholderLegendary Artifact Creature — InsectCreature — Faerie RogueCreature — Elf ShamanLegendary Creature — Human Noble WarriorCreature — WolfLegendary Planeswalker — ChandraLegendary ArtifactArtifact Creature — Equipment KirinLegendary Planeswalker — KioraEnchantment Creature — SirenLegendary Planeswalker — TamiyoLegendary Artifact Creature — HumanKindred Enchantment — FaerieEnchantment Creature — SpiritLegendary Creature — Human GamerCreature — Merfolk ShamanLegendary Artifact Creature — RobotCreature — Human RogueCreature — Elf DruidCreature — Demon BerserkerCreature — VampireLegendary Planeswalker — SarkhanEnchantment — RoomLegendary Creature — Human KnightCreature — Human BerserkerCreature — HorrorCreature — Faerie NobleLegendary Creature — DemonSorcery — LessonCreature — Angel DetectiveArtifact Creature — Assembly-WorkerLegendary Creature — Lizard ShamanKindred Enchantment — ElfCreature — AngelCreature — DrakeEnchantment — Aura CurseLand — Urza's TowerLegendary Creature — Goblin PirateCreature — LeechCreature — Human ShamanCreature — Thalakos Soldier ScoutCreature — DragonLegendary Creature — Human Warrior AllyLegendary Creature — Phyrexian PraetorCreature — KrakenLegendary Creature — NightmareLegendary Creature — Human Soldier MercenaryLegendary Planeswalker — RalLegendary Creature — Human ClericLegendary Creature — HumanLegendary Creature — Human ArtificerCreature — Elf Warrior AllyLegendary Creature — Human Mutant WizardLegendary Creature — Spirit WarriorCreature — Elemental LhurgoyfCreature — ZombieLegendary Creature — Human DetectiveInstant — AdventureLegendary Creature — SpiritCreature — FishArtifact Creature — DragonLegendary Creature — Human CitizenCreature — PegasusCreature — Elemental ShamanCreature — Lizard WizardLegendary Artifact Creature — CybermanArtifact Creature — Phyrexian WurmLegendary Creature — Snake Elf ScoutLegendary Creature — Lizard DetectiveCreature — ShadeLegendary Creature — Human AssassinLegendary Creature — Vampire DemonCreature — Phyrexian Human ArtificerCreature — DjinnLegendary Creature — MutantCreature — Bird ScoutLegendary Creature — Phyrexian Dragon SkeletonLegendary Creature — Moogle WarriorLegendary Creature — ElementalArtifact Creature — Human WizardCreature — Human MercenaryCreature — Merfolk WizardCreature — Human MonkCreature — Skeleton WarriorCreature — SpecterLegendary Creature — Dragon GodCreature — GoblinCreature — Orc PirateCreature — BirdCreature — Giant BerserkerLegendary Creature — Human WarlockCreature — Merfolk RogueLegendary Creature — Dinosaur TurtleLegendary Creature — Orc WarriorLegendary Planeswalker — VivienEnchantment Creature — Avatar HorrorLegendary Creature — Human Faerie DetectiveCreature — Human ClericCreature — ElfCreature — UnicornCreature — Fungus DinosaurLegendary Creature — Phyrexian VampireLegendary Creature — Human RogueCreature — Elf WizardCreature — Merfolk ScoutCreature — Human WarriorLegendary Creature — Siren PirateCreature — Crab SkeletonLegendary Creature — Human NobleLegendary Artifact Creature — Robot DogLegendary Creature — Goblin WarriorCreature — Vampire ClericCreature — DemonLegendary Creature — Elder GiantLegendary Creature — ApeCreature — Human KnightCreature — AvatarCreature — SerpentLegendary Planeswalker — BolasArtifact Creature — Phyrexian AvatarLegendary Planeswalker — AjaniLegendary Creature — Frog DruidEnchantment Creature — DryadCreature — Elf ScoutCreature — BeastCreature — OozeCreature — Astartes WarriorLegendary Creature — Snake DruidCreature — Elf Druid RogueLegendary Creature — Human WarriorCreature — Cat SoldierKindred Sorcery — GoblinLegendary Creature — AngelLegendary Creature — Spirit ClericCreature — Efreet ShamanCreature — Phyrexian DemonLegendary Planeswalker — RowanCreature — Giant WizardArtifact Creature — ConstructCreature — Phyrexian Insect HorrorCreature — Sphinx WizardArtifact Creature — InsectCreature — Vampire Cleric AllyCreature — ImpEnchantment Creature — ArchonCreature — Phyrexian WizardCreature — Human PirateCreature — NightmareLegendary Creature — Rat NinjaCreature — Plant ElementalCreature — Human Rogue WerewolfSorcery — ArcaneLegendary Creature — BeastCreature — TreefolkCreature — InsectCreature — ArchonLand — PlanetLand — Island SwampCreature — Minotaur PirateCreature — Cat BeastCreature — ElkCreature — Phyrexian HorrorCreature — Soltari SoldierLegendary Creature — BearCreature — Dragon WarriorLegendary Creature — Shapeshifter DetectiveLegendary Creature — Orc ShamanLegendary Planeswalker — BasriLegendary Creature — Hydra AvatarCreature — Homarid WarriorLegendary Artifact — EquipmentCreature — Dinosaur EmployeeCreature — Merfolk NobleLegendary Planeswalker — TezzeretCreature — Zombie ManticoreCreature — SalamanderBattle — SiegeSnow LandLand — DesertLegendary Creature — Spider Human HeroCreature — HydraCreature — Kor WizardLegendary Creature — Human PirateCreature — GiantCreature — Harpy BeastCreature — ChimeraLegendary Creature — Human Knight MercenaryLegendary Creature — Phyrexian BeastCreature — Vampire ShamanLegendary Planeswalker — LilianaCreature — LizardCreature — Eldrazi DroneLegendary Creature — Cat WarlockCreature — Vampire WarlockLegendary Planeswalker — ElspethLegendary Creature — Cat DragonLegendary Creature — Elf DruidLegendary Creature — Human BerserkerCreature — Elemental WhaleCreature — Kor RogueLegendary Creature — Phyrexian Horror MinionCreature — Human Soldier ArcherArtifact Creature — Phyrexian HorrorArtifact — TreasureLegendary LandCreature — SquirrelArtifact Creature — Equipment OgrePlane — WildfireCreature — Ogre MercenaryLegendary Artifact Creature — Synth KnightArtifact Creature — SpellshaperLegendary Creature — Goblin NobleLegendary Creature — Zombie WizardLegendary Creature — Human ScientistCreature — Dwarf WarriorCreature — Skeleton PirateEnchantment Creature — ZombieLegendary Creature — GodArtifact Creature — GnomeCreature — Cat NightmareCreature — Orc WarriorLegendary Creature — DragonWorld EnchantmentLegendary Creature — Mutant WarriorLegendary Planeswalker — VraskaLegendary Creature — Elf WizardLegendary Creature — Rabbit SoldierLegendary Creature — Elder DragonLegendary Planeswalker — LukkaLegendary Creature — Avatar WarriorCreature — Dwarf ScoutLegendary Planeswalker — SorinLand — Mountain ForestLegendary Creature — HydraInstant — TrapInstant — LessonLegendary Creature — Bird ScoutLegendary Creature — Rat WarlockArtifact — AttractionLegendary Creature — Vampire AssassinArtifact Creature — ShapeshifterLegendary EnchantmentLegendary Creature — Elemental HorrorCreature — Illusion SliverLegendary Creature — Human SoldierCreature — Centaur SpiritLegendary Creature — Human MinionCreature — HumanCreature — Phyrexian WurmLand — GateCreature — FungusCreature — Goblin SoldierCreature — LeviathanCreature — Zombie WizardCreature — Cat ArcherCreature — Rhino WarriorCreature — Giant ClericCreature — Astartes WizardCreature — Zombie KnightLegendary Creature — Angel AllyCreature — Snake HydraCreature — Troll SkeletonCreature — Snake WizardCreature — Mouse BardCreature — MonkeyLegendary Creature — FaerieCreature — Insect HorrorLegendary Enchantment Creature — ShrineCreature — Centaur WarriorCreature — OupheLegendary Creature — EldraziCreature — Vampire WizardCreature — Goblin RogueCreature — Vampire KnightArtifact Creature — SphinxCreature — Spirit DetectiveLegendary Creature — Wombat Bat ChameleonLegendary Creature — Human BarbarianLegendary Creature — Demon PrimarchLegendary Creature — Human Elf ShamanCreature — Elf ArcherLegendary Enchantment Creature — GodCreature — Zombie Coward GuestCreature — Soltari ClericLegendary Creature — Human SamuraiCreature — Fish HorrorCreature — FaerieCreature — Elf KnightLegendary Creature — Elf ScoutLegendary Planeswalker — MinscSchemeCreature — Faerie AdvisorLand — CaveCreature — Elemental KnightCreature — Rhino BeastArtifact Creature — BirdCreature — Dog ScoutCreature — Horse IllusionCreature — Orc AthleteCreature — Human DruidCreature — Wraith KnightCreature — Dragon WizardLegendary Planeswalker — ArlinnCreature — MerfolkLegendary Creature — Vampire NobleCreature — Bird MutantCreature — Human NinjaLegendary Planeswalker — DarettiCreature — Eldrazi TurtleLegendary Creature — Moonfolk WizardLegendary Creature — Giant ShamanArtifact Creature — Scarecrow GuestLegendary Creature — Dwarf AdvisorLegendary Creature — Phyrexian HorrorLegendary Creature — SerpentLegendary Creature — Human PerformerCreature — Treefolk WarriorCreature — Goblin WizardCreature — Ogre Samurai MercenaryCreature — Fungus SliverLegendary Creature — Human MonkLegendary Creature — PhoenixCreature — Ogre RogueLegendary Creature — Phyrexian Human WizardLegendary Planeswalker — GarrukCreature — Plant HydraEnchantment Creature — InsectLegendary Creature — Goblin SorcererLegendary Creature — Human AdvisorEnchantment Creature — HumanCreature — Goblin PirateCreature — TrollLegendary Creature — Elemental AvatarLegendary Creature — Human Faerie ScoutCreature — PhoenixCreature — Ape ShamanLegendary Creature — Human NinjaCreature — Zombie MutantLegendary Creature — Time Lord DoctorEnchantment Creature — MoonfolkArtifact Creature — Dinosaur ThopterCreature — Kavu SoldierLegendary Creature — Human ScoutLegendary Creature — DryadCreature — Bird SoldierKindred Sorcery — EldraziCreature — Vampire Warrior AllyCreature — Angel WarriorEnchantment — ClassLegendary Creature — Merfolk ShamanCreature — CatCreature — Lizard WarriorLegendary Planeswalker — KayaArtifact Creature — MyrCreature — Elemental BeastCreature — Human AdvisorArtifact Creature — GargoyleLegendary Creature — Zombie ElfCreature — Kor SoldierCreature — Faerie KnightLegendary Planeswalker — SamutCreature — Bird SpiritKindred Enchantment — ElementalCreature — Zombie GiantLegendary Planeswalker — TeferiCreature — Elemental SpiritArtifact — ClueLegendary Creature — Human Faerie RogueCreature — TrilobiteKindred Enchantment — Treefolk AuraCreature — Bird InsectLegendary Creature — Giant WarriorLegendary Planeswalker — NahiriConspiracyCreature — Antelope BeastArtifact Creature — Phyrexian MyrLegendary Planeswalker — AshiokLegendary Creature — Goblin ShamanLegendary Creature — Human ShamanLegendary Planeswalker — NissaArtifact Creature — DogArtifact Creature — JellyfishLegendary Creature — Cyclops HomunculusLegendary Creature — Skeleton RogueCreature — Frog WarriorLegendary Creature — WolfArtifact Creature — GolemCreature — OxEnchantment Creature — EggEnchantment Creature — NightmareLegendary Creature — Spirit DragonCreature — DevilArtifact Creature — Equipment RhinoLegendary Creature — VampireCreature — Zombie Cat WarriorLegendary Artifact Creature — NecronCreature — Horror SpiritCreature — Dryad HorrorCreature — VarmintCreature — Dauthi RogueCreature — Vampire AssassinLegendary Creature — Elder DemonCreature — Human DetectiveCreature — JellyfishCreature — Human Scout RangerCreature — Phyrexian KavuCreature — Eldrazi HorrorLegendary Creature — Elemental ShamanCreature — Zombie BeastLegendary Creature — Zombie AssassinLegendary Planeswalker — JayaLand — SphereLegendary Creature — Wraith NobleCreature — Snake WarriorCreature — GriffinLegendary Artifact Creature — ConstructCreature — SpiderLegendary Creature — Elemental DemonLand Creature — Forest DryadCreature — TyranidCreature — Dwarf ArtificerLegendary Creature — Merfolk GodLegendary Creature — Giant NobleCreature — GremlinLegendary Creature — Vampire ClericCreature — RatCreature — BadgerLegendary Creature — Elder DinosaurCreature — Vedalken ArtificerLand — Swamp ForestLegendary Creature — Bird WizardLegendary Creature — Azra AssassinLegendary Creature — ShapeshifterLegendary Creature — Giant ScoutCreature — Zombie MercenaryLegendary Creature — Dinosaur Cat NightmareCreature — WallCreature — Squirrel WarlockCreature — Weird DetectiveLegendary Creature — Elder WizardLegendary Creature — Crab MutantEnchantment Creature — Saga OxCreature — Spirit ClericLegendary Planeswalker — KarnLegendary Creature — Human Wizard WarriorArtifact Creature — JuggernautLegendary Planeswalker — NixilisCreature — Mouse WarriorArtifact Creature — ClericCreature — Dragon TurtleLegendary Planeswalker — DomriLegendary Creature — Aetherborn VampireCreature — ThrullCreature — Human RangerLegendary Creature — Human Soldier WarriorLegendary Creature — Human Elf ClericCreature — Vampire HorrorCreature — Zombie Jackal ClericLegendary Creature — Elder Giant DogPlane — DominariaCreature — Phyrexian MinionLegendary Creature — Phyrexian Zombie ElfArtifact LandLegendary Creature — Bird WarlockLegendary Creature — Rat RogueLegendary Creature — Avatar WizardLand — PlainsLegendary Artifact Creature — Human WizardArtifact Creature — Human ArtificerSnow SorceryCreature — Giant MercenaryCreature — Elemental GiantCreature — Human Rogue ArtificerCreature — Zombie DrakeCreature — Cat SealTribal Enchantment — ElementalLegendary Creature — Dragon SpiritCreature — Lizard WarlockCreature — Dog ShamanCreature — Human HorrorLegendary Creature — Merfolk WizardCreature — Spirit AvatarLegendary Creature — Turtle ShamanArtifact — Equipment VehicleLegendary Planeswalker — UginLegendary Creature — GoblinLegendary Creature — Angel HorrorLegendary Creature — Giant BarbarianLegendary Creature — Dwarf WarriorLegendary Creature — Human Rebel MonkEnchantment Creature — Goblin ShamanCreature — Human BardCreature — Ogre WarriorLegendary Artifact Creature — GolemCreature — OctopusCreature — WerewolfLegendary Creature — Cat Nightmare BeastCreature — Cat ClericLegendary Creature — Angel ArtificerLegendary Creature — Spirit AdvisorLegendary Creature — Human Scientist VillainLegendary Artifact — VehicleCreature — Insect WarriorEnchantment Creature — Saga DragonLegendary Creature — Human ArcherLegendary Creature — Angel WizardLegendary Artifact Creature — Phyrexian ArtificerCreature — Goblin ShamanLand — Plains IslandCreature — Siren PirateLegendary Creature — Faerie WarlockCreature — NephilimCreature — Human AssassinLegendary Creature — Human DoctorCreature — Porcupine PerformerCreature — Spirit WizardCreature — DryadLegendary Creature — Bear DruidLegendary Creature — HorrorCreature — Goblin WarlockEnchantment — CaseCreature — Vampire SkeletonLegendary Creature — DogLegendary Creature — Human RebelCreature — Elemental BoarArtifact Creature — DalekPlane — KephalaiLegendary Creature — Orc SoldierCreature — Moonfolk WizardCreature — WeirdCreature — Squid HorrorPlane — RathCreature — IllusionLegendary Creature — Elemental BoarLegendary Enchantment ArtifactLegendary Creature — Dragon KnightLegendary Creature — Elemental FoxLegendary Creature — Kor AdvisorCreature — Elf AssassinLegendary Creature — Phyrexian ElementalCreature — Cat SpiritLegendary Creature — Elemental DinosaurCreature — Treefolk DruidPhenomenonLegendary Creature — Phyrexian Elf NobleCreature — Bird WarlockCreature — Faerie WarlockLegendary Creature — Dwarf WizardLegendary Creature — Goblin RebelLegendary Creature — Nightmare BeastLegendary Creature — Centaur SpiritArtifact — BobbleheadCreature — Ape WarriorCreature — Faerie ShapeshifterCreature — Zombie NinjaCreature — Phyrexian Human ClericCreature — Eldrazi OctopusCreature — HippogriffLegendary Creature — WizardCreature — SkeletonEnchantment Creature — Human WizardCreature — Human BarbarianCreature — Devil DetectiveCreature — Human ScoutLegendary Creature — Azra WarlockLegendary Creature — Dragon AvatarCreature — Lizard ShamanCreature — Faerie WizardLegendary Creature — Spirit GodLegendary Creature — Dwarf NobleCreature — Serpent DragonCreature — Minotaur BerserkerCreature — ScorpionLegendary Creature — Vampire AllyCreature — Plant ZombieLegendary Creature — GorgonEnchantment — Aura CartoucheLegendary Creature — Human Artificer AdvisorArtifact Creature — Spider ToyLegendary Creature — Human Alien ShapeshifterLegendary Creature — Frog HorrorLegendary Creature — Snake ShamanLegendary Creature — Cat AvatarArtifact Creature — AngelCreature — GargoyleLegendary Creature — Halfling KnightLegendary Creature — Elf WarriorCreature — Treefolk ShamanCreature — Dwarf ShamanLegendary Creature — Leviathan CrabCreature — Human NobleLegendary Creature — Spirit NobleLegendary Planeswalker — OkoCreature — KoboldLegendary Planeswalker — HuatliLegendary Creature — Lizard VillainCreature — Nightmare SphinxCreature — Elf PerformerLegendary SorceryLegendary Planeswalker — KaitoArtifact Creature — Human ClericEnchantment Creature — Snake LamiaCreature — Goblin ArtificerArtifact Creature — RobotLegendary Creature — Illusion RogueCreature — Elemental WolfInstant Creature — AlienLegendary Creature — Yeti BerserkerLegendary Creature — Ogre DemonEnchantment Creature — Saga DogLegendary Creature — Elf ShamanCreature — Spirit HorrorLegendary Creature — Elemental SorcererLegendary Creature — AssassinLegendary Creature — Devil GodArtifact Creature — Clue PlantLegendary Creature — Treefolk DruidLegendary Planeswalker — AminatouCreature — Eldrazi ProcessorLegendary Creature — Zombie DragonCreature — Human Soldier RangerLegendary Artifact Creature — GnomeLegendary Creature — Vampire PerformerCreature — Zombie CrocodileCreature — Vampire DragonLegendary Creature — KrakenCreature — Human Shaman AllyLegendary Creature — Zombie SnakeArtifact Creature — Phyrexian DogLegendary Creature — Phyrexian HydraLegendary Creature — Treefolk ShamanCreature — Cat ScoutCreature — Crab BeastCreature — Dinosaur BeastCreature — Elephant ClericCreature — Nightmare AngelLegendary Planeswalker — TashaCreature — Angel SoldierCreature — NightstalkerLegendary Creature — Squirrel DruidCreature — Dauthi JackalCreature — Human Rogue AllyEnchantment Creature — Human SoldierCreature — Insect WrestlerCreature — Illusion HorseCreature — Goblin Warrior AllyCreature — Human Shaman WerewolfCreature — Kor Warrior KnightCreature — LhurgoyfLegendary Creature — Vampire WarriorCreature — Phyrexian ZombieCreature — Djinn WizardLegendary Creature — Goblin RogueLegendary Creature — Elf PerformerLand — LairArtifact Creature — Phyrexian GolemKindred Enchantment — Eldrazi AuraCreature — Zombie VampireArtifact Creature — WallLegendary Creature — Merfolk NobleCreature — Dryad WarriorCreature — Elemental DogCreature — Treefolk SoldierLegendary Creature — Elf RogueCreature — Kithkin WizardCreature — Vampire BerserkerPlane — IquatanaLegendary Creature — Beast MountCreature — Phyrexian SharkLegendary Creature — Human Archer RangerLegendary PlaneswalkerCreature — Human CitizenLegendary Creature — Ogre WizardCreature — Min

In [8]:
len(df['base_type'].unique())

59

In [28]:
df1 = df.drop(columns='type')

In [29]:
df1

,uuid,frameVersion,setCode,isOnlineOnly,isTextless,keywords,name,text,rules,base_type
0,18d320b3-3b97-5cfc-959c-66e22911627b,2015,RIX,False,False,NaN,Reckless Rage,Reckless Rage deals 4 damage to target creatur...,You can’t cast Reckless Rage unless you choose...,Instant
1,e4eb8663-1d62-5abc-bbfe-ff9dd2de43c0,2015,PTHB,False,False,"Flying, Lifelink",Dream Trawler,"Flying, lifelink\nWhenever you draw a card, th...",You can activate Dream Trawler's last ability ...,Creature
2,64f3de78-c603-5aa9-bd74-9feafc32f476,2015,NCC,False,False,NaN,Generous Gift,Destroy target permanent. Its controller creat...,If the target permanent is an illegal target b...,Instant
3,38d1f975-1b3b-5047-8328-61f5ca71ddba,2015,SLD,False,False,NaN,Leeching Sliver,"Whenever a Sliver you control attacks, defendi...","Abilities that Slivers grant, as well as power...",Creature
4,9729bc88-7ca2-5ad1-bcf4-fd5c2b88f0ad,2015,SNC,False,False,"Haste, Deathtouch",Maestros Diabolist,"Deathtouch, haste\nWhenever this creature atta...",Maestros Diabolist's triggered ability has an ...,Creature
...,...,...,...,...,...,...,...,...,...,...
14243,9bf0b366-1471-5484-8016-fe1e5e66ccaa,2015,WOE,False,False,Bargain,Johann's Stopgap,"Bargain (You may sacrifice an artifact, enchan...",The cost-reduction ability of Johann's Stopgap...,Sorcery
14244,233784b1-3db1-5ed6-9262-04c55217c7d9,1997,APC,False,False,NaN,Ceta Sanctuary,"At the beginning of your upkeep, if you contro...","The ability has you draw one or two cards, but...",Enchantment
14245,f811931c-810f-58cd-86e4-50be261ec920,2015,KTK,False,False,NaN,Smoke Teller,{1}{U}: Look at target face-down creature.,You could target a creature you control with S...,Creature
14246,6fb939cc-6091-5399-9106-fa863d212cb9,2003,MRD,False,False,Entwine,Journey of Discovery,Choose one —\n• Search your library for up to ...,If you cast an entwined Journey of Discovery u...,Sorcery
14247,76d70ede-6a05-580a-9f12-5aec082b5fab,2015,TLA,False,False,"Mill, Defender",Platypus-Bear,"Defender\nWhen this creature enters, mill two ...","Once Platypus-Bear has attacked, it will remai...",Creature

battle, plane, schemes, conspiracy, phenomenon, vanguard, instant creature, summon, host creature, ongoing scheme, elemental instant, poly artifact, artifact enchantment, summon licid, basic creature, land planeswalker

In [ ]:
df1['base_type'] = df1['base_type'].replace({
    'instant': 'Instant',
    'Legendary Creature': 'Creature', 
    'Artifact Creature': 'Creature',
    'Legendary Artifact Land': 'Land',
    'Legendary Enchantment': 'Enchantment',
    'Enchantment Creature':'Creature',
    'Legendary Artifact Creature': 'Creature',
    'Legendary Artifact': 'Artifact',
    'Kindred Enchantment': 'Enchantment',
    'Kindred Sorcery': 'Sorcery',
    'Snow Land': 'Land',
    'Legendary Land': 'Land',
    'World Enchantment': 'Enchantment',
    'Legendary Enchantment Creature': 'Creature',
    'Land Creature': 'Land',
    'Artifact Land': 'Land',
    'Snow Sorcery': 'Sorcery',
    'Tribal Enchantment': 'Enchantment',
    'Legendary Enchantment Artifact': 'Enchantment',
    'Legendary Sorcery': 'Sorcery',
    'Kindred Instant': 'Instant',
    'Enchantment Land': 'Land',
    'Snow Creature': 'Creature',
    'Legendary Snow Creature': 'Creature',
    'Snow Enchantment': 'Enchantment',
    'Tribal Instant': 'Instant',
    'Legendary Snow Enchantment': 'Enchantment',
    'Kindred Artifact': 'Artifact',
    'Legendary Instant': 'Instant',
    'Legendary Snow Land': 'Land',
    'Snow Instant': 'Instant',
    'Legendary Artifact Planeswalker': 'Planeswalker',
    'Snow Artifact': 'Artifact',
    'Snow Artifact Creature': 'Creature',
    'Legendary Planeswalker': 'Planeswalker'

})

In [36]:
df1['base_type'].unique()

array(['Instant', 'Creature', 'Enchantment', 'Sorcery', 'Land',
       'Artifact', 'Planeswalker', 'Battle', 'Plane', 'Scheme',
       'Conspiracy', 'Phenomenon', 'Instant Creature', 'Summon',
       'Host Creature', 'Ongoing Scheme', 'Vanguard', 'Elemental Instant',
       'Poly Artifact', 'Artifact Enchantment', 'Summon Licid',
       'Basic Creature', 'Land Planeswalker', 'Summon Wolf'], dtype=object)

In [37]:
unwanted_types = [
    'Battle', 'Plane', 'Scheme', 'Conspiracy', 'Phenomenon', 
    'Instant Creature', 'Summon', 'Host Creature', 'Ongoing Scheme', 
    'Vanguard', 'Elemental Instant', 'Poly Artifact', 'Artifact Enchantment', 
    'Summon Licid', 'Basic Creature', 'Land Planeswalker', 'Summon Wolf'
]

df1 = df1[~df1['base_type'].isin(unwanted_types)]

In [38]:
df1['base_type'].unique()

array(['Instant', 'Creature', 'Enchantment', 'Sorcery', 'Land',
       'Artifact', 'Planeswalker'], dtype=object)

In [42]:
df1 = df1.set_index('uuid')

In [43]:
df1

,frameVersion,setCode,isOnlineOnly,isTextless,keywords,name,text,rules,base_type
uuid,,,,,,,,,
18d320b3-3b97-5cfc-959c-66e22911627b,2015,RIX,False,False,NaN,Reckless Rage,Reckless Rage deals 4 damage to target creatur...,You can’t cast Reckless Rage unless you choose...,Instant
e4eb8663-1d62-5abc-bbfe-ff9dd2de43c0,2015,PTHB,False,False,"Flying, Lifelink",Dream Trawler,"Flying, lifelink\nWhenever you draw a card, th...",You can activate Dream Trawler's last ability ...,Creature
64f3de78-c603-5aa9-bd74-9feafc32f476,2015,NCC,False,False,NaN,Generous Gift,Destroy target permanent. Its controller creat...,If the target permanent is an illegal target b...,Instant
38d1f975-1b3b-5047-8328-61f5ca71ddba,2015,SLD,False,False,NaN,Leeching Sliver,"Whenever a Sliver you control attacks, defendi...","Abilities that Slivers grant, as well as power...",Creature
9729bc88-7ca2-5ad1-bcf4-fd5c2b88f0ad,2015,SNC,False,False,"Haste, Deathtouch",Maestros Diabolist,"Deathtouch, haste\nWhenever this creature atta...",Maestros Diabolist's triggered ability has an ...,Creature
...,...,...,...,...,...,...,...,...,...
9bf0b366-1471-5484-8016-fe1e5e66ccaa,2015,WOE,False,False,Bargain,Johann's Stopgap,"Bargain (You may sacrifice an artifact, enchan...",The cost-reduction ability of Johann's Stopgap...,Sorcery
233784b1-3db1-5ed6-9262-04c55217c7d9,1997,APC,False,False,NaN,Ceta Sanctuary,"At the beginning of your upkeep, if you contro...","The ability has you draw one or two cards, but...",Enchantment
f811931c-810f-58cd-86e4-50be261ec920,2015,KTK,False,False,NaN,Smoke Teller,{1}{U}: Look at target face-down creature.,You could target a creature you control with S...,Creature
6fb939cc-6091-5399-9106-fa863d212cb9,2003,MRD,False,False,Entwine,Journey of Discovery,Choose one —\n• Search your library for up to ...,If you cast an entwined Journey of Discovery u...,Sorcery
76d70ede-6a05-580a-9f12-5aec082b5fab,2015,TLA,False,False,"Mill, Defender",Platypus-Bear,"Defender\nWhen this creature enters, mill two ...","Once Platypus-Bear has attacked, it will remai...",Creature

In [45]:
df1.to_csv('mtg_cleaned.csv')